default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fclone_development

production:
  <<: *default
  database: fclone_production
  username: fclone
  password: <%= ENV['FCLONE_DATABASE_PASSWORD'] %>
